In [4]:
import tensorflow as tf


In [8]:

full_temp_input = tf.constant([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
full_temp_input

<tf.Tensor: shape=(1, 11), dtype=int32, numpy=array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)>

In [9]:
full_temp_input[:, 1:4]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [10]:
full_temp_input[:, 4]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>

In [12]:
t = 8
n = min(4, t)
step_range = tf.range(t - n, t)
step_range

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>

In [13]:
tf.gather(full_temp_input, step_range, axis=1)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[5, 6, 7, 8]], dtype=int32)>

In [2]:
B = 1
H = 3
W = 3
n = 5

t = 2
zeros = tf.zeros(shape=(max(n - t, 0), H, W, 1), dtype=tf.float32)
real = tf.random.normal(shape=(min(t, n), H, W, 1), dtype=tf.float32)
result = tf.concat([zeros, real], axis=0)
result.shape

2024-07-09 18:45:35.245062: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1015 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0


TensorShape([5, 3, 3, 1])

In [3]:
result[:, 1:]

<tf.Tensor: shape=(5, 2, 3, 1), dtype=float32, numpy=
array([[[[ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ]]],


       [[[ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ]]],


       [[[ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ]]],


       [[[ 1.77385   ],
         [ 0.75705665],
         [-0.25937018]],

        [[ 0.3490627 ],
         [-1.1044705 ],
         [-0.09342398]]],


       [[[-0.9537608 ],
         [-0.8639037 ],
         [ 1.7518018 ]],

        [[-0.9457039 ],
         [ 1.7293448 ],
         [ 0.2496509 ]]]], dtype=float32)>

In [29]:
max(n - t, 0)

3

In [39]:
t+n

7

In [60]:
label = tf.random.normal(shape=(10, H, W, 1))

In [66]:
label[-1:4]

<tf.Tensor: shape=(0, 3, 3, 1), dtype=float32, numpy=array([], shape=(0, 3, 3, 1), dtype=float32)>