In [1]:
import tensorflow as tf


2024-07-09 03:52:26.782515: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-09 03:52:26.832651: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-09 03:52:26.832687: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-09 03:52:26.833892: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-09 03:52:26.841784: I tensorflow/core/platform/cpu_feature_guar

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [9]:

full_temp_input = tf.constant([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
full_temp_input

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)>

In [12]:
t = 8
n = min(4, t)
step_range = tf.range(t - n, t)
step_range

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>

In [13]:
tf.gather(full_temp_input, step_range, axis=1)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[5, 6, 7, 8]], dtype=int32)>

In [58]:
B = 1
H = 3
W = 3
n = 5

t = 2
zeros = tf.zeros(shape=(max(n - t, 0), H, W, 1), dtype=tf.float32)
real = tf.random.normal(shape=(min(t, n), H, W, 1), dtype=tf.float32)
result = tf.concat([zeros, real], axis=0)
result.shape

TensorShape([5, 3, 3, 1])

In [29]:
max(n - t, 0)

3

In [39]:
t+n

7

In [60]:
label = tf.random.normal(shape=(10, H, W, 1))

In [66]:
label[-1:4]

<tf.Tensor: shape=(0, 3, 3, 1), dtype=float32, numpy=array([], shape=(0, 3, 3, 1), dtype=float32)>